### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by fabricetheytaz** [openfoodfacts/openfoodfacts-cordova-app#15]
Application inutilisable sur "d'anciens" téléphone. Out of Memory lors de la prise de vue de photo sur mon Samsung Galaxy S2... snif...

**Comment by teolemon** [comment]
java.lang.OutOfMemoryError
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:640)
at android.graphics.Bitmap.createBitmap(Bitmap.java:586)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:466)
at org.apache.cordova.camera.CameraLauncher.getScaledBitmap(CameraLauncher.java:790)
at org.apache.cordova.camera.CameraLauncher.processResultFromCamera(CameraLauncher.java:405)
at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:629)
at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:771)
at android.app.Activity.dispatchActivityResult(Activity.java:5390)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3201)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3248)
at android.app.ActivityThread.access$1200(ActivityThread.java:140)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4921)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
at dalvik.system.NativeStart.main(Native Method)

**Comment by teolemon** [comment]
java.lang.OutOfMemoryError
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
at android.graphics.Bitmap.createBitmap(Bitmap.java:719)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:595)
at org.apache.cordova.camera.CameraLauncher.getScaledBitmap(CameraLauncher.java:790)
at org.apache.cordova.camera.CameraLauncher.processResultFromCamera(CameraLauncher.java:405)
at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:629)
at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:784)
at android.app.Activity.dispatchActivityResult(Activity.java:5423)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3385)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3432)
at android.app.ActivityThread.access$1300(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1253)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5146)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
at dalvik.system.NativeStart.main(Native Method)
